/**
 * @fileName : RefreshController.ets
 * @author : @cxy
 * @date : 2024/9/19
 * @description : 文件描述
 */


export class RefreshController {
  static refreshWords: string[] = []
  scroller: ListScroller = new ListScroller()
  setHasmore: (hasmore: boolean) => void = () => {
  }
  finishRefresh: () => void = () => {
  }
  hideLoadMore: (hide: boolean) => void = () => {
  }
  onRefresh: () => void = () => {
  }
  scrollToIndex: (value: number, smooth?: boolean, align?: ScrollAlign, options?: ScrollToIndexOptions) => void =
    () => {

    }
}